### PR TITLE
Vic 232 UI display specific error messages for login registration

### PR DESCRIPTION
**Pull request by BryanObe**
To Test:

1. Login to confirm login works as expected (then logout)
2. Enter invalid credentials to login. Note that form clears and error message appears stating related error
3. Generate different error messaged based on other bad form data (no password, bad email format, etc.)
4. Go to Registration
5. Attempt to register with an email already existing. Note error message displayed
6. Attempt other bad data input (e.g. a password that is the same as the email name, the password 'password', etc.). Note that error messages correspond to invalid data entry

### CODE REVIEW

**Review by bee-mcc — CHANGES_REQUESTED** [review]
Looks good, the only thing I noticed is that if you try to log in incorrectly, then no matter what you do after that (try to log in correctly) you are provided with the "This field may not be blank." error (even when there is text in the field.

**Comment by bee-mcc** [comment]
Also I merged the changes which are on main into this to check if they work, and they seem to

**Comment by BryanObe** [comment]
> Looks good, the only thing I noticed is that if you try to log in incorrectly, then no matter what you do after that (try to log in correctly) you are provided with the "This field may not be blank." error (even when there is text in the field.

This is a valid bug to fix, however I am going to prioritize other issues. I will however add a issue to the jira board corresponding to this bug

**Review by bee-mcc — APPROVED** [review]
!

**Pull request merged**
